# Generated by Django 5.1.4 on 2024-12-23 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_complaints', to='core.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='dslcard',
            unique_together={('msag', 'card_number')},
        ),
        migrations.AlterUniqueTogether(
            name='dslport',
            unique_together={('dsl_card', 'port_number')},
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('complaint_text', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_complaints', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Complaint',
                'verbose_name_plural': 'Customer Complaints',
            },
        ),
        migrations.CreateModel(
            name='DSLPortHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('deallocation_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_history', to='core.customer')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_history', to='core.dslport')),
            ],
            options={
                'verbose_name': 'DSL Port Allocation History',
                'verbose_name_plural': 'DSL Port Allocation Histories',
            },
        ),
    ]
