# Generated by Django 5.1.4 on 2024-12-26 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_email_alter_complaint_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DSLRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('package', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsl_requests', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ModemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Issued', 'Issued')], default='Available', max_length=50)),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.CharField(max_length=255)),
                ('scheduled_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Assigned', max_length=50)),
                ('dsl_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dslrequest')),
            ],
        ),
    ]
