# Generated by Django 5.1.4 on 2024-12-31 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_digitaldocuments_dslrequest_modeminventory_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='dsl_port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.dslport'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='modem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.modeminventory'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='msag',
            field=models.ForeignKey(default=1981, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.msag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='dsl_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='core.dslrequest'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Assigned', max_length=50),
        ),
    ]
