# Generated by Django 5.1.4 on 2025-01-06 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dslcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='card_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.dslcard'),
            preserve_default=False,
        ),
    ]
