# Generated by Django 5.1.4 on 2025-01-08 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workorder_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='phone_number',
            field=models.ForeignKey(
                null=True,  # Allow null values for existing rows
                on_delete=django.db.models.deletion.CASCADE,
                related_name='work_order',
                to='core.customer',
            ),
        ),
    ]
